### ISSUE TITLE
Allow configuration of date formats

### ISSUE THREAD

**Issue by infotexture** [oxygenxml/oxygen-dita-prolog-updater#11]
I'd prefer to use ISO 8601 date formats (YYYY-MM-DD) in the prolog elements, but I don't see any way to configure that in the preferences or plug-in code.

**Comment by DunaMariusCosmin** [comment]
Hi, @infotexture! 
Thanks for the feedback. 
We will add a field for configure the date format in the next version of this plugin.

**Comment by DunaMariusCosmin** [comment]
The new release version(1.0.9) contains a new configure option for the date format.

**Comment by infotexture** [comment]
Excellent, thanks! 🙏
