### ISSUE TITLE
Option to overwrite existing prolog

### ISSUE THREAD

**Issue by mhowes82** [oxygenxml/oxygen-dita-prolog-updater#16]
Thank you very much for providing this plugin and continuing to update it! I've only done limited testing, but it appears that saving a changed DITA topic with an existing prolog appends the revised element with the current date. This means that each day we save the topic, the list of revised elements grows. I know we could simply delete the older revised elements, but is there an option to simply replace the existing revised element with the current date?

**Comment by DunaMariusCosmin** [comment]
Hi @mhowes82,
First, thank you for the feedback. 
I register an internal issue for this improvement and we will add this in the next version of the add-on.

**Comment by mhowes82** [comment]
Has work on the issue above already begun? After working with the tool for a few months now, we think it would also be useful, or more useful than addressing the issue above, to be able to set the number of revised elements to keep in the prolog. For example, we've decided to only keep the two most recent revised elements to prevent the list from growing too long. Would this be a possible change or perhaps a change in place of the issue above? Thanks again for a great plugin!

**Comment by DunaMariusCosmin** [comment]
I added your proposal on our internal issue. We will add an option to control the maximum number of  revised elements that will be kept in the document.

**Comment by mhowes82** [comment]
Hi DunaMariusCosmin, 
Could you tell me when can we expect the next release of this plugin? It's become an integral part of our workflow, so we could really use the feature in my last comment on Dec 18. Are you open to compensation or a donation to get this feature added soon?

**Comment by DunaMariusCosmin** [comment]
Hi @mhowes82,
We will try to add this feature in the next few weeks. I will notify you when it's ready.

**Comment by DunaMariusCosmin** [comment]
Hi @mhowes82, 
In the new release(1.0.11), I added a new option to limit the list of revised elements from the updated document. By default, this option is disable, but you can enable this from the plugin's configuration page. 
Let me know if it works like you expected.

**Comment by mhowes82** [comment]
Hi DunaMariusCosmin,
Thank you so much for getting this feature out so soon! I did a quick test setting the revision limit to 2 and it worked perfectly! Thank you again! Looking forward to future updates.
