### ISSUE TITLE
Ability to include/exclude DITA file types

### ISSUE THREAD

**Issue by mhowes82** [oxygenxml/oxygen-dita-prolog-updater#18]
Wondering if you could add an option to include/exclude files the the updater changes?  For example, if we only want the revision elements added to topic files (e.g. task, concept, reference), but not DITA maps, we could exclude .ditamap. Thanks!

**Comment by raducoravu** [comment]
In the Oxygen Preferences->"Plugins / DITA Prolog Updater" you will find a checkbox to exclude updating the prolog in DITA Maps.

**Comment by mhowes82** [comment]
Thanks Radu!
