### ISSUE TITLE
Allow "creator" and "contributor" @type values to be configured

### ISSUE THREAD

**Issue by chrispy-snps** [oxygenxml/oxygen-dita-prolog-updater#20]
Starting with DITA 1.2, the `@type` attribute is not constrained to predefined values, as noted here:

https://docs.oasis-open.org/dita/v1.2/os/spec/langref/author.html

We would like to use `owner` instead of `creator`, as documentation sometimes gets reassigned from one writer to another. Could you please allow the plugin's `creator` and `contributor` values to be configured?

Thanks!

**Comment by DunaMariusCosmin** [comment]
Hi Chris,
We have just released version 1.1.0. and this Improves the process so that an additional author (contributor) cannot be added if they are already specified as the primary (creator) author.
Regards,
Cosmin
