### ISSUE TITLE
Prevent "contributor" entry if author already exists as "creator"

### ISSUE THREAD

**Issue by chrispy-snps** [oxygenxml/oxygen-dita-prolog-updater#21]
Currently, the plugin will add the author as a `contributor` when a document is modified, even if they are already listed as the `creator`:

```
  <prolog>
    <author type="creator">chrispy</author>
    <author type="contributor">chrispy</author>
  </prolog>
```

Could you please provide a way to disable an author being listed twice, whether by default or as an option?

Thanks!

**Comment by DunaMariusCosmin** [comment]
Hi Chris,
We have just released version 1.1.0 and this contains 2 new options to customise the value of the "type" attribute.
Regards,
Cosmin
