### ISSUE TITLE
Add a preferences page

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/oxygen-dita-prolog-updater#5]
A plugin can add its own preferences page to Oxygen:

https://www.oxygenxml.com/doc/versions/19.1/ug-editor/topics/optionpage-plugin.html

Using such a preferences page users can configure their author name (defaults to the system user name), and maybe some checkboxes they can use in order to configure if they want the author name to be added to the prolog, if they want the created/modification dates to be added and so on....

**Comment by DunaMariusCosmin** [comment]
Fixed in: 56c14a7ac1f0920c933ecd4cf06491b21290a806

**Comment by raducoravu** [comment]
There are about 2 types of DITA Maps, the regular maps which have the root named "map" and bookmaps (we have a sample in the Oxygen samples/dita/it-book) which instead of "topicmeta" use "bookmeta".

**Comment by DunaMariusCosmin** [comment]
Fixed in: ee8f54af318a5540b01822efbcde9603d063f607
